# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'flight_manage.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_FlightManagerForm(object):
    def setupUi(self, FlightManagerForm):
        FlightManagerForm.setObjectName("FlightManagerForm")
        FlightManagerForm.resize(811, 489)
        self.gridLayout = QtWidgets.QGridLayout(FlightManagerForm)
        self.gridLayout.setContentsMargins(20, 30, 20, 20)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, -1, -1, 35)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(FlightManagerForm)
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(28)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.gridLayout.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(5, -1, 5, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(FlightManagerForm)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setTextFormat(QtCore.Qt.RichText)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.deploc = QtWidgets.QLineEdit(FlightManagerForm)
        self.deploc.setMinimumSize(QtCore.QSize(20, 0))
        self.deploc.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.deploc.setFont(font)
        self.deploc.setObjectName("deploc")
        self.horizontalLayout_3.addWidget(self.deploc)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.label_3 = QtWidgets.QLabel(FlightManagerForm)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setTextFormat(QtCore.Qt.RichText)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.arrloc = QtWidgets.QLineEdit(FlightManagerForm)
        self.arrloc.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.arrloc.setFont(font)
        self.arrloc.setText("")
        self.arrloc.setObjectName("arrloc")
        self.horizontalLayout_3.addWidget(self.arrloc)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.searchflight = QtWidgets.QPushButton(FlightManagerForm)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.searchflight.setFont(font)
        self.searchflight.setObjectName("searchflight")
        self.horizontalLayout_3.addWidget(self.searchflight)
        self.gridLayout.addLayout(self.horizontalLayout_3, 1, 0, 1, 1)
        self.flighttable = QtWidgets.QTableWidget(FlightManagerForm)
        self.flighttable.setAlternatingRowColors(True)
        self.flighttable.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.flighttable.setRowCount(10)
        self.flighttable.setObjectName("flighttable")
        self.flighttable.setColumnCount(6)
        item = QtWidgets.QTableWidgetItem()
        self.flighttable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.flighttable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.flighttable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.flighttable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.flighttable.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.flighttable.setHorizontalHeaderItem(5, item)
        self.flighttable.horizontalHeader().setStretchLastSection(True)
        self.flighttable.verticalHeader().setVisible(False)
        self.gridLayout.addWidget(self.flighttable, 2, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, 10, -1, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.addButton = QtWidgets.QPushButton(FlightManagerForm)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.addButton.setFont(font)
        self.addButton.setObjectName("addButton")
        self.horizontalLayout.addWidget(self.addButton)
        self.updateButton = QtWidgets.QPushButton(FlightManagerForm)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.updateButton.setFont(font)
        self.updateButton.setObjectName("updateButton")
        self.horizontalLayout.addWidget(self.updateButton)
        self.delButton = QtWidgets.QPushButton(FlightManagerForm)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.delButton.setFont(font)
        self.delButton.setObjectName("delButton")
        self.horizontalLayout.addWidget(self.delButton)
        self.gridLayout.addLayout(self.horizontalLayout, 3, 0, 1, 1)

        self.retranslateUi(FlightManagerForm)
        QtCore.QMetaObject.connectSlotsByName(FlightManagerForm)

    def retranslateUi(self, FlightManagerForm):
        _translate = QtCore.QCoreApplication.translate
        FlightManagerForm.setWindowTitle(_translate("FlightManagerForm", "Form"))
        self.label.setText(_translate("FlightManagerForm", "航班管理"))
        self.label_2.setText(_translate("FlightManagerForm", "出发城市"))
        self.label_3.setText(_translate("FlightManagerForm", "达到城市"))
        self.searchflight.setText(_translate("FlightManagerForm", "查询"))
        item = self.flighttable.horizontalHeaderItem(0)
        item.setText(_translate("FlightManagerForm", "航班号"))
        item = self.flighttable.horizontalHeaderItem(1)
        item.setText(_translate("FlightManagerForm", "出发城市"))
        item = self.flighttable.horizontalHeaderItem(2)
        item.setText(_translate("FlightManagerForm", "达到城市"))
        item = self.flighttable.horizontalHeaderItem(3)
        item.setText(_translate("FlightManagerForm", "出发时间"))
        item = self.flighttable.horizontalHeaderItem(4)
        item.setText(_translate("FlightManagerForm", "达到时间"))
        item = self.flighttable.horizontalHeaderItem(5)
        item.setText(_translate("FlightManagerForm", "详情"))
        self.addButton.setText(_translate("FlightManagerForm", "增加航班"))
        self.updateButton.setText(_translate("FlightManagerForm", "修改航班"))
        self.delButton.setText(_translate("FlightManagerForm", "删除航班"))

