# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'flight_information.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_FlightInfomationForm(object):
    def setupUi(self, FlightInfomationForm):
        FlightInfomationForm.setObjectName("FlightInfomationForm")
        FlightInfomationForm.resize(562, 502)
        self.gridLayout_8 = QtWidgets.QGridLayout(FlightInfomationForm)
        self.gridLayout_8.setContentsMargins(20, 40, 20, 20)
        self.gridLayout_8.setVerticalSpacing(10)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.label = QtWidgets.QLabel(FlightInfomationForm)
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(22)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout_8.addWidget(self.label, 0, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(0, 20, 0, 20)
        self.gridLayout.setSpacing(10)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(FlightInfomationForm)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.fli_num_lE = QtWidgets.QLineEdit(FlightInfomationForm)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.fli_num_lE.setFont(font)
        self.fli_num_lE.setObjectName("fli_num_lE")
        self.gridLayout.addWidget(self.fli_num_lE, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(FlightInfomationForm)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.dep_loc_lE = QtWidgets.QLineEdit(FlightInfomationForm)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.dep_loc_lE.setFont(font)
        self.dep_loc_lE.setObjectName("dep_loc_lE")
        self.gridLayout.addWidget(self.dep_loc_lE, 1, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(FlightInfomationForm)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 2, 1, 1)
        self.arr_loc_lE = QtWidgets.QLineEdit(FlightInfomationForm)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.arr_loc_lE.setFont(font)
        self.arr_loc_lE.setObjectName("arr_loc_lE")
        self.gridLayout.addWidget(self.arr_loc_lE, 1, 3, 1, 1)
        self.label_5 = QtWidgets.QLabel(FlightInfomationForm)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 2, 0, 1, 1)
        self.dep_time_lE = QtWidgets.QLineEdit(FlightInfomationForm)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.dep_time_lE.setFont(font)
        self.dep_time_lE.setObjectName("dep_time_lE")
        self.gridLayout.addWidget(self.dep_time_lE, 2, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(FlightInfomationForm)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 2, 2, 1, 1)
        self.arr_time_lE = QtWidgets.QLineEdit(FlightInfomationForm)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.arr_time_lE.setFont(font)
        self.arr_time_lE.setObjectName("arr_time_lE")
        self.gridLayout.addWidget(self.arr_time_lE, 2, 3, 1, 1)
        self.gridLayout_8.addLayout(self.gridLayout, 1, 0, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(FlightInfomationForm)
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(12)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.economy_tab = QtWidgets.QWidget()
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.economy_tab.setFont(font)
        self.economy_tab.setObjectName("economy_tab")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.economy_tab)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.eco_remain_lE = QtWidgets.QLineEdit(self.economy_tab)
        self.eco_remain_lE.setObjectName("eco_remain_lE")
        self.gridLayout_2.addWidget(self.eco_remain_lE, 2, 1, 1, 1)
        self.eco_price_lE = QtWidgets.QLineEdit(self.economy_tab)
        self.eco_price_lE.setObjectName("eco_price_lE")
        self.gridLayout_2.addWidget(self.eco_price_lE, 0, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.economy_tab)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 0, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.economy_tab)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 2, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.economy_tab)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 1, 0, 1, 1)
        self.eco_order_lE = QtWidgets.QLineEdit(self.economy_tab)
        self.eco_order_lE.setObjectName("eco_order_lE")
        self.gridLayout_2.addWidget(self.eco_order_lE, 1, 1, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        self.tabWidget.addTab(self.economy_tab, "")
        self.business_tab = QtWidgets.QWidget()
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.business_tab.setFont(font)
        self.business_tab.setObjectName("business_tab")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.business_tab)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_14 = QtWidgets.QLabel(self.business_tab)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.gridLayout_3.addWidget(self.label_14, 0, 0, 1, 1)
        self.busi_order_lE = QtWidgets.QLineEdit(self.business_tab)
        self.busi_order_lE.setObjectName("busi_order_lE")
        self.gridLayout_3.addWidget(self.busi_order_lE, 1, 1, 1, 1)
        self.busi_remain_lE = QtWidgets.QLineEdit(self.business_tab)
        self.busi_remain_lE.setObjectName("busi_remain_lE")
        self.gridLayout_3.addWidget(self.busi_remain_lE, 2, 1, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.business_tab)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.gridLayout_3.addWidget(self.label_16, 2, 0, 1, 1)
        self.busi_price_lE = QtWidgets.QLineEdit(self.business_tab)
        self.busi_price_lE.setObjectName("busi_price_lE")
        self.gridLayout_3.addWidget(self.busi_price_lE, 0, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.business_tab)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.gridLayout_3.addWidget(self.label_12, 1, 0, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_3, 0, 0, 1, 1)
        self.tabWidget.addTab(self.business_tab, "")
        self.Frist_tab = QtWidgets.QWidget()
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.Frist_tab.setFont(font)
        self.Frist_tab.setObjectName("Frist_tab")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.Frist_tab)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_19 = QtWidgets.QLabel(self.Frist_tab)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.gridLayout_4.addWidget(self.label_19, 0, 0, 1, 1)
        self.frist_price_lE = QtWidgets.QLineEdit(self.Frist_tab)
        self.frist_price_lE.setObjectName("frist_price_lE")
        self.gridLayout_4.addWidget(self.frist_price_lE, 0, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.Frist_tab)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.gridLayout_4.addWidget(self.label_13, 1, 0, 1, 1)
        self.frist_order_lE = QtWidgets.QLineEdit(self.Frist_tab)
        self.frist_order_lE.setObjectName("frist_order_lE")
        self.gridLayout_4.addWidget(self.frist_order_lE, 1, 1, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.Frist_tab)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.gridLayout_4.addWidget(self.label_17, 2, 0, 1, 1)
        self.frist_remain_lE = QtWidgets.QLineEdit(self.Frist_tab)
        self.frist_remain_lE.setObjectName("frist_remain_lE")
        self.gridLayout_4.addWidget(self.frist_remain_lE, 2, 1, 1, 1)
        self.gridLayout_7.addLayout(self.gridLayout_4, 0, 0, 1, 1)
        self.tabWidget.addTab(self.Frist_tab, "")
        self.gridLayout_8.addWidget(self.tabWidget, 2, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(278, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.add_fli_inf = QtWidgets.QPushButton(FlightInfomationForm)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.add_fli_inf.setFont(font)
        self.add_fli_inf.setObjectName("add_fli_inf")
        self.horizontalLayout.addWidget(self.add_fli_inf)
        self.gridLayout_8.addLayout(self.horizontalLayout, 3, 0, 1, 1)

        self.retranslateUi(FlightInfomationForm)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(FlightInfomationForm)

    def retranslateUi(self, FlightInfomationForm):
        _translate = QtCore.QCoreApplication.translate
        FlightInfomationForm.setWindowTitle(_translate("FlightInfomationForm", "航班信息"))
        self.label.setText(_translate("FlightInfomationForm", "航班信息"))
        self.label_2.setText(_translate("FlightInfomationForm", "航班号"))
        self.label_3.setText(_translate("FlightInfomationForm", "出发地点"))
        self.label_4.setText(_translate("FlightInfomationForm", "达到地点"))
        self.label_5.setText(_translate("FlightInfomationForm", "出发时间"))
        self.label_6.setText(_translate("FlightInfomationForm", "达到时间"))
        self.label_8.setText(_translate("FlightInfomationForm", "票价"))
        self.label_10.setText(_translate("FlightInfomationForm", "剩余数量"))
        self.label_11.setText(_translate("FlightInfomationForm", "已订数量"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.economy_tab), _translate("FlightInfomationForm", "经济舱"))
        self.label_14.setText(_translate("FlightInfomationForm", "票价"))
        self.label_16.setText(_translate("FlightInfomationForm", "剩余数量"))
        self.label_12.setText(_translate("FlightInfomationForm", "已订数量"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.business_tab), _translate("FlightInfomationForm", "商务舱"))
        self.label_19.setText(_translate("FlightInfomationForm", "票价"))
        self.label_13.setText(_translate("FlightInfomationForm", "已订数量"))
        self.label_17.setText(_translate("FlightInfomationForm", "剩余数量"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Frist_tab), _translate("FlightInfomationForm", "头等舱"))
        self.add_fli_inf.setText(_translate("FlightInfomationForm", "确认"))

