# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'new_passenger.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_New_Pa_Form(object):
    def setupUi(self, New_Pa_Form):
        New_Pa_Form.setObjectName("New_Pa_Form")
        New_Pa_Form.resize(461, 383)
        New_Pa_Form.setStyleSheet("QPushButton\n"
"{\n"
"}")
        self.layoutWidget = QtWidgets.QWidget(New_Pa_Form)
        self.layoutWidget.setGeometry(QtCore.QRect(50, 50, 193, 50))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("images/新旅客.png"))
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.layoutWidget1 = QtWidgets.QWidget(New_Pa_Form)
        self.layoutWidget1.setGeometry(QtCore.QRect(90, 140, 282, 149))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.p_name_Edit = QtWidgets.QLineEdit(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(10)
        self.p_name_Edit.setFont(font)
        self.p_name_Edit.setObjectName("p_name_Edit")
        self.horizontalLayout_3.addWidget(self.p_name_Edit)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_6 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_6.addWidget(self.label_6)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.comboBox = QtWidgets.QComboBox(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(10)
        self.comboBox.setFont(font)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.horizontalLayout_2.addWidget(self.comboBox)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_2)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.p_ID_Edit = QtWidgets.QLineEdit(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(9)
        self.p_ID_Edit.setFont(font)
        self.p_ID_Edit.setObjectName("p_ID_Edit")
        self.horizontalLayout_4.addWidget(self.p_ID_Edit)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_5 = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.p_tele_Edit = QtWidgets.QLineEdit(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(10)
        self.p_tele_Edit.setFont(font)
        self.p_tele_Edit.setObjectName("p_tele_Edit")
        self.horizontalLayout_5.addWidget(self.p_tele_Edit)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.add_info = QtWidgets.QPushButton(New_Pa_Form)
        self.add_info.setGeometry(QtCore.QRect(280, 310, 93, 28))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.add_info.setFont(font)
        self.add_info.setStyleSheet("QPushButton{}")
        self.add_info.setAutoDefault(False)
        self.add_info.setDefault(False)
        self.add_info.setFlat(False)
        self.add_info.setObjectName("add_info")

        self.retranslateUi(New_Pa_Form)
        QtCore.QMetaObject.connectSlotsByName(New_Pa_Form)

    def retranslateUi(self, New_Pa_Form):
        _translate = QtCore.QCoreApplication.translate
        New_Pa_Form.setWindowTitle(_translate("New_Pa_Form", "Form"))
        self.label.setText(_translate("New_Pa_Form", "新增用户"))
        self.label_3.setText(_translate("New_Pa_Form", "姓名:"))
        self.label_6.setText(_translate("New_Pa_Form", "性别:"))
        self.comboBox.setItemText(0, _translate("New_Pa_Form", "男"))
        self.comboBox.setItemText(1, _translate("New_Pa_Form", "女"))
        self.label_4.setText(_translate("New_Pa_Form", "身份证号:"))
        self.label_5.setText(_translate("New_Pa_Form", "手机:"))
        self.add_info.setText(_translate("New_Pa_Form", "添加"))

