# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_LoginForm(object):
    def setupUi(self, LoginForm):
        LoginForm.setObjectName("LoginForm")
        LoginForm.resize(472, 389)
        self.layoutWidget = QtWidgets.QWidget(LoginForm)
        self.layoutWidget.setGeometry(QtCore.QRect(100, 50, 263, 271))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("images/旅客订票.png"))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.admin_rB = QtWidgets.QRadioButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.admin_rB.setFont(font)
        self.admin_rB.setObjectName("admin_rB")
        self.gridLayout.addWidget(self.admin_rB, 1, 1, 1, 1)
        self.loginButton = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.loginButton.setFont(font)
        self.loginButton.setObjectName("loginButton")
        self.gridLayout.addWidget(self.loginButton, 2, 0, 1, 1)
        self.registerButton = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.registerButton.setFont(font)
        self.registerButton.setObjectName("registerButton")
        self.gridLayout.addWidget(self.registerButton, 2, 1, 1, 1)
        self.user_rB = QtWidgets.QRadioButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.user_rB.setFont(font)
        self.user_rB.setChecked(True)
        self.user_rB.setObjectName("user_rB")
        self.gridLayout.addWidget(self.user_rB, 1, 0, 1, 1)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setContentsMargins(5, -1, -1, -1)
        self.formLayout.setObjectName("formLayout")
        self.label1 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.label1.setFont(font)
        self.label1.setObjectName("label1")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label1)
        self.label2 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.label2.setFont(font)
        self.label2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label2.setObjectName("label2")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label2)
        self.user_name = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Adamas")
        font.setPointSize(12)
        self.user_name.setFont(font)
        self.user_name.setObjectName("user_name")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.SpanningRole, self.user_name)
        self.user_password = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Adamas")
        font.setPointSize(12)
        self.user_password.setFont(font)
        self.user_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.user_password.setObjectName("user_password")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.SpanningRole, self.user_password)
        self.gridLayout.addLayout(self.formLayout, 0, 0, 1, 2)
        self.verticalLayout.addLayout(self.gridLayout)

        self.retranslateUi(LoginForm)
        QtCore.QMetaObject.connectSlotsByName(LoginForm)

    def retranslateUi(self, LoginForm):
        _translate = QtCore.QCoreApplication.translate
        LoginForm.setWindowTitle(_translate("LoginForm", "机票预定系统"))
        self.label.setText(_translate("LoginForm", "机票预定系统"))
        self.admin_rB.setText(_translate("LoginForm", "管理员"))
        self.loginButton.setText(_translate("LoginForm", "登陆"))
        self.registerButton.setText(_translate("LoginForm", "注册"))
        self.user_rB.setText(_translate("LoginForm", "用户"))
        self.label1.setText(_translate("LoginForm", "用户名:"))
        self.label2.setText(_translate("LoginForm", "密码:"))

