# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'passenger.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_PassengerForm(object):
    def setupUi(self, PassengerForm):
        PassengerForm.setObjectName("PassengerForm")
        PassengerForm.resize(761, 494)
        self.gridLayout = QtWidgets.QGridLayout(PassengerForm)
        self.gridLayout.setContentsMargins(20, 20, 20, 20)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, 20, -1, 10)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(PassengerForm)
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("images/常旅客.png"))
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.label = QtWidgets.QLabel(PassengerForm)
        font = QtGui.QFont()
        font.setFamily("晴圆")
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(486, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.gridLayout.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(0, 20, 0, 5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.new_pass = QtWidgets.QPushButton(PassengerForm)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.new_pass.setFont(font)
        self.new_pass.setObjectName("new_pass")
        self.horizontalLayout.addWidget(self.new_pass)
        self.update_pas = QtWidgets.QPushButton(PassengerForm)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.update_pas.setFont(font)
        self.update_pas.setObjectName("update_pas")
        self.horizontalLayout.addWidget(self.update_pas)
        self.del_pas = QtWidgets.QPushButton(PassengerForm)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.del_pas.setFont(font)
        self.del_pas.setObjectName("del_pas")
        self.horizontalLayout.addWidget(self.del_pas)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        self.passengertable = QtWidgets.QTableWidget(PassengerForm)
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(16)
        self.passengertable.setFont(font)
        self.passengertable.setAlternatingRowColors(True)
        self.passengertable.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.passengertable.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.passengertable.setRowCount(10)
        self.passengertable.setObjectName("passengertable")
        self.passengertable.setColumnCount(4)
        item = QtWidgets.QTableWidgetItem()
        self.passengertable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.passengertable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.passengertable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.passengertable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(6)
        item.setFont(font)
        self.passengertable.setItem(0, 2, item)
        self.passengertable.horizontalHeader().setCascadingSectionResizes(False)
        self.passengertable.horizontalHeader().setDefaultSectionSize(170)
        self.passengertable.horizontalHeader().setMinimumSectionSize(100)
        self.passengertable.horizontalHeader().setSortIndicatorShown(True)
        self.passengertable.horizontalHeader().setStretchLastSection(True)
        self.passengertable.verticalHeader().setVisible(False)
        self.passengertable.verticalHeader().setDefaultSectionSize(50)
        self.passengertable.verticalHeader().setMinimumSectionSize(80)
        self.gridLayout.addWidget(self.passengertable, 2, 0, 1, 1)

        self.retranslateUi(PassengerForm)
        QtCore.QMetaObject.connectSlotsByName(PassengerForm)

    def retranslateUi(self, PassengerForm):
        _translate = QtCore.QCoreApplication.translate
        PassengerForm.setWindowTitle(_translate("PassengerForm", "常用旅客"))
        self.label.setText(_translate("PassengerForm", "常用旅客"))
        self.new_pass.setText(_translate("PassengerForm", "新增旅客"))
        self.update_pas.setText(_translate("PassengerForm", "修改资料"))
        self.del_pas.setText(_translate("PassengerForm", "删除旅客"))
        item = self.passengertable.horizontalHeaderItem(0)
        item.setText(_translate("PassengerForm", "旅客姓名"))
        item = self.passengertable.horizontalHeaderItem(1)
        item.setText(_translate("PassengerForm", "性别"))
        item = self.passengertable.horizontalHeaderItem(2)
        item.setText(_translate("PassengerForm", "身份证号"))
        item = self.passengertable.horizontalHeaderItem(3)
        item.setText(_translate("PassengerForm", "电话"))
        __sortingEnabled = self.passengertable.isSortingEnabled()
        self.passengertable.setSortingEnabled(False)
        self.passengertable.setSortingEnabled(__sortingEnabled)

