# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ticket_information.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_TicketInformationForm(object):
    def setupUi(self, TicketInformationForm):
        TicketInformationForm.setObjectName("TicketInformationForm")
        TicketInformationForm.resize(554, 385)
        self.gridLayout_3 = QtWidgets.QGridLayout(TicketInformationForm)
        self.gridLayout_3.setContentsMargins(20, 20, 20, 20)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_9 = QtWidgets.QLabel(TicketInformationForm)
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(22)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.gridLayout_3.addWidget(self.label_9, 0, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(TicketInformationForm)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(TicketInformationForm)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.name_IE = QtWidgets.QLineEdit(TicketInformationForm)
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(12)
        self.name_IE.setFont(font)
        self.name_IE.setReadOnly(True)
        self.name_IE.setObjectName("name_IE")
        self.gridLayout.addWidget(self.name_IE, 0, 1, 1, 1)
        self.ID_IE = QtWidgets.QLineEdit(TicketInformationForm)
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(9)
        self.ID_IE.setFont(font)
        self.ID_IE.setReadOnly(True)
        self.ID_IE.setObjectName("ID_IE")
        self.gridLayout.addWidget(self.ID_IE, 1, 1, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout, 1, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(253, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 1, 1, 1, 2)
        self.line = QtWidgets.QFrame(TicketInformationForm)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_3.addWidget(self.line, 2, 0, 1, 3)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_3 = QtWidgets.QLabel(TicketInformationForm)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 0, 0, 1, 1)
        self.fli_num_IE = QtWidgets.QLineEdit(TicketInformationForm)
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(12)
        self.fli_num_IE.setFont(font)
        self.fli_num_IE.setReadOnly(True)
        self.fli_num_IE.setObjectName("fli_num_IE")
        self.gridLayout_2.addWidget(self.fli_num_IE, 0, 1, 1, 1)
        self.update_ticket_fli = QtWidgets.QPushButton(TicketInformationForm)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.update_ticket_fli.setFont(font)
        self.update_ticket_fli.setObjectName("update_ticket_fli")
        self.gridLayout_2.addWidget(self.update_ticket_fli, 0, 2, 1, 2)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 0, 4, 1, 1)
        self.label_5 = QtWidgets.QLabel(TicketInformationForm)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 1, 0, 1, 1)
        self.dep_loc_IE = QtWidgets.QLineEdit(TicketInformationForm)
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(12)
        self.dep_loc_IE.setFont(font)
        self.dep_loc_IE.setReadOnly(True)
        self.dep_loc_IE.setObjectName("dep_loc_IE")
        self.gridLayout_2.addWidget(self.dep_loc_IE, 1, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(TicketInformationForm)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 1, 2, 1, 1)
        self.arr_loc_IE = QtWidgets.QLineEdit(TicketInformationForm)
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(12)
        self.arr_loc_IE.setFont(font)
        self.arr_loc_IE.setReadOnly(True)
        self.arr_loc_IE.setObjectName("arr_loc_IE")
        self.gridLayout_2.addWidget(self.arr_loc_IE, 1, 3, 1, 2)
        self.label_4 = QtWidgets.QLabel(TicketInformationForm)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 2, 0, 1, 1)
        self.dep_time_IE = QtWidgets.QLineEdit(TicketInformationForm)
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(12)
        self.dep_time_IE.setFont(font)
        self.dep_time_IE.setReadOnly(True)
        self.dep_time_IE.setObjectName("dep_time_IE")
        self.gridLayout_2.addWidget(self.dep_time_IE, 2, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(TicketInformationForm)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 2, 2, 1, 1)
        self.arr_time_IE = QtWidgets.QLineEdit(TicketInformationForm)
        font = QtGui.QFont()
        font.setFamily("微软雅黑 Light")
        font.setPointSize(12)
        self.arr_time_IE.setFont(font)
        self.arr_time_IE.setReadOnly(True)
        self.arr_time_IE.setObjectName("arr_time_IE")
        self.gridLayout_2.addWidget(self.arr_time_IE, 2, 3, 1, 2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_8 = QtWidgets.QLabel(TicketInformationForm)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout.addWidget(self.label_8)
        self.comboBox = QtWidgets.QComboBox(TicketInformationForm)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.comboBox.setFont(font)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.horizontalLayout.addWidget(self.comboBox)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.gridLayout_2.addLayout(self.horizontalLayout, 3, 0, 1, 2)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem3, 3, 2, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 3, 0, 1, 3)
        spacerItem4 = QtWidgets.QSpacerItem(153, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem4, 4, 1, 1, 1)
        self.updateButton = QtWidgets.QPushButton(TicketInformationForm)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.updateButton.setFont(font)
        self.updateButton.setObjectName("updateButton")
        self.gridLayout_3.addWidget(self.updateButton, 4, 2, 1, 1)

        self.retranslateUi(TicketInformationForm)
        self.comboBox.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(TicketInformationForm)

    def retranslateUi(self, TicketInformationForm):
        _translate = QtCore.QCoreApplication.translate
        TicketInformationForm.setWindowTitle(_translate("TicketInformationForm", "订单信息"))
        self.label_9.setText(_translate("TicketInformationForm", "订单信息"))
        self.label_2.setText(_translate("TicketInformationForm", "身份证号"))
        self.label.setText(_translate("TicketInformationForm", "姓名"))
        self.label_3.setText(_translate("TicketInformationForm", "航班号"))
        self.update_ticket_fli.setText(_translate("TicketInformationForm", "修改航班"))
        self.label_5.setText(_translate("TicketInformationForm", "出发地点"))
        self.label_6.setText(_translate("TicketInformationForm", "达到地点"))
        self.label_4.setText(_translate("TicketInformationForm", "出发时间"))
        self.label_7.setText(_translate("TicketInformationForm", "达到时间"))
        self.label_8.setText(_translate("TicketInformationForm", "舱位等级"))
        self.comboBox.setItemText(0, _translate("TicketInformationForm", "经济舱"))
        self.comboBox.setItemText(1, _translate("TicketInformationForm", "商务舱"))
        self.comboBox.setItemText(2, _translate("TicketInformationForm", "头等舱"))
        self.updateButton.setText(_translate("TicketInformationForm", "修改"))

